version: "3.8"

services:
  backend:
    build: ./kitnet
    container_name: kitnet-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_kitnet:5432/kitnet
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:?SPRING_DATASOURCE_USERNAME is required}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:?SPRING_DATASOURCE_PASSWORD is required}
    ports:
      - "8090:8089"
    restart: always
    networks:
      - rede-local

  frontend:
    build: ./sis-kitnet
    container_name: kitnet-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: always
    networks:
      - rede-local

networks:
  rede-local:
    external: true