pipeline {
    agent any

    environment {
        IMAGE_NAME = 'kitnet-backend'
        JWT_SECRET = credentials('JWT_SECRET')
        SONAR_QUBE_URL = 'http://localhost:9000'
        DSONAR_LOGIN = credentials('DSONAR_LOGIN')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('kitnet') {
                    sh 'chmod +x ./mvnw && ./mvnw clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SONAR_LOCAL') {
                    dir('kitnet') {
                        sh """
                        ${tool 'SONAR_SCANNER'}/bin/sonar-scanner \\
                        -Dsonar.projectKey=SIS_KITNET_BACKEND \\
                        -Dsonar.host.url=${env.SONAR_QUBE_URL} \\
                        -Dsonar.login=${env.DSONAR_LOGIN} \\
                        -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                sleep(10)
                timeout(time: 3, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('kitnet') {
                    sh 'docker build -t $IMAGE_NAME .'
                    sh 'docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    # Garante que a rede existe
                    docker network inspect rede-local >/dev/null 2>&1 || docker network create rede-local

                    # Para e remove container antigo
                                        docker stop $IMAGE_NAME || true
                                        docker rm $IMAGE_NAME || true

                    # Sobe novo container
                    docker run -d -p 8090:8089 \
                                            --name $IMAGE_NAME \
                      --network rede-local \
                      -e JWT_SECRET="${JWT_SECRET}" \
                                            $IMAGE_NAME:latest
                '''
            }
        }
    }

    post {
        success {
            echo "Pipeline executado com sucesso! Build ${BUILD_NUMBER}."
        }
        failure {
            echo "Pipeline falhou! Verifique os logs das stages."
        }
        always {
            echo "Pipeline finalizada."
        }
    }
}