pipeline {
    agent any

    environment {
        JWT_SECRET = credentials('JWT_SECRET')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('kitnet') {
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('kitnet') {
                    sh 'docker build -t kitnet-backend .'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                sh """
                docker stop kitnet-backend || true
                docker rm kitnet-backend || true
                docker run -d -p 8090:8089 \
                  --name kitnet-backend \
                  --network rede-local \
                  -e JWT_SECRET=${JWT_SECRET} \
                  kitnet-backend
                '''
                """
            }
        }
    }
}
