spring.profiles.active=prod

# Swagger UI customizacao
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.doc-expansion=list
springdoc.swagger-ui.display-request-duration=true
springdoc.api-docs.path=/v3/api-docs

# Note: For production, set SPRING_PROFILES_ACTIVE=prod in the environment

# JWT properties
# 1 hora em milissegundos
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000