spring.profiles.active=prod


# Swagger UI customização
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.doc-expansion=list
springdoc.swagger-ui.display-request-duration=true
springdoc.api-docs.path=/v3/api-docs

# Note: For production, set SPRING_PROFILES_ACTIVE=prod in the environment